export const FETCH_ACTION_SUCCESS = "FETCH_ACTION_SUCCESS";
export const FETCH_ACTION_FAIL = "FETCH_ACTION_FAIL";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
