export const FETCH_ACTION_SUCCESS = "FETCH_ACTION_SUCCESS";
export const FETCH_ACTION_FAIL = "FETCH_ACTION_FAIL";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const MAIN_SELECTION = "MAIN_SELECTION";

export const CUSTOM_ORDER_BACK = "CUSTOM_ORDER_BACK";
export const SELECT_CARBOHYDRATE = "SELECT_CARBOHYDRATE";
export const SELECT_CONDIMENTS = "SELECT_CONDIMENTS";
export const SELECT_DRESSING = "SELECT_DRESSING";
export const SELECT_PROTEIN = "SELECT PROTEIN";
