export const FETCH_ACTION_SUCCESS = "FETCH_ACTION_SUCCESS";
export const FETCH_ACTION_FAIL = "FETCH_ACTION_FAIL";
export const UPDATE_MENU = "UPDATE_MENU";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const MAIN_SELECTION = "MAIN_SELECTION";

export const CUSTOM_ORDER_BACK = "CUSTOM_ORDER_BACK";
export const RESET_ORDER = "RESET_ORDER";
export const SENDING_ORDER = "SENDING_ORDER";
export const UPDATE_CUSTOM_PHASE = "UPDATE_CUSTOM_PHASE";
